
api:
  jsonplaceholder:
    domain: "api.coingecko.com"
    key: "CG-e3UPwLBrbex3k2tUyouwLJiM"
    rediskey: "crytpo:coingecko:coins-markets"
    endpoints:
      coin: "/api/v3/coins/markets"

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0


##part 1
##https://www.coingecko.com/en/developers/dashboard
#peter_demo	CG-e3UPwLBrbex3k2tUyouwLJiM

#part 2
#https://www.coingecko.com/api/documentation
#/coins/markets

#part 3

#part 4

##http://localhost:8080/crypto/coingecko/api/v1/coins?currency=usd&ids=bitcoin,ethereum
server:
  servlet:
    context-path: /crypto/coingecko


