server:
  port: 8085

api:
  jsonplaceholder:
    domain: "finnhub.io"
    key: "cnaqg1hr01ql0f8ae20gcnaqg1hr01ql0f8ae210"
    endpoints:
      company: "/api/v1/stock/profile2"
      stock: "/api/v1/quote"

##http://localhost:8085/api/v1/stock?symbol=AAPL
##http://localhost:8085/api/v1/stock?symbol=EXCOF